njalla_api_token: ENC[AES256_GCM,data:guvbIxvasat7RPXoJIM21ieogB4KPToMhPQcBitNKH3SDRU49y2jFg==,iv:4DKNaanmdYbN1HYquY8GONlBb6SsaGgMpRGAMCzMsTw=,tag:P3cESwrVmXT9xbib9V71vw==,type:str]
keycloak_db_password: ENC[AES256_GCM,data:K0nw9N1Zs1epsjGJeB7rECHXJb1IeUOp,iv:UbIp5FYTh7s+JLlPiAM4dVoo5M2Bb4YOtaASaigoYt4=,tag:ImsU5c9xMV5yXBv++vs9UA==,type:str]
keycloak_redis_password: ENC[AES256_GCM,data:z/9tRSVr7dlGvqYJM71FNVNtP2KXaP/J,iv:l19nVlbIwQhg9Wf2S5xqOPm5bfkc1dYM0iJwQpMJ3Eg=,tag:T6PtMENvJPthR5tbV6GiyQ==,type:str]
keycloak_secret_key: ENC[AES256_GCM,data:vpXEf5DyMd6kZxNlx7pxEaoRSL8BceAw4cq/HjlWH04=,iv:vpiu8FnOjBPQ0s4KYcLDIZ9hEu5c43MoBTgoTZ7rsGo=,tag:BFCP6odvnGJdpc6uFaoTsg==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:yXzKALAwnAASSWH9vqiCYSyWPT17eVUn,iv:Dy73iRhVF4a9Nr1/pvObGZZxu0hn55/CQCZ/fUyqZ1w=,tag:lCfjl9XyLBoOan9zg2zciw==,type:str]
alert_smtp_user: ENC[AES256_GCM,data:U1LYddTeRA1l,iv:5vN/3gK+AE5VA/y/fMiwIwizlhTDL8tDwKlnZcvi7HA=,tag:XodCJAmt6dHeeGIkMNPEXA==,type:str]
alert_smtp_password: ENC[AES256_GCM,data:08Kf0B3oRu/W+3t5VrrQ6NcQf6/XfrCoa/cYh0nuZbWoKzEwRNZtsUE3BRA=,iv:f4sjoXXqTK8fgmRdrlvUW7V0flFUV+hXBw8WnDUwR00=,tag:c63YdLXlRPbmNsFFSeQwmQ==,type:str]
sops:
    age:
        - recipient: age10q0tj8gewf6rgx8plzz0lh9z8mamha6zw5qa7k2ea0d7q7kt8f5srrzmmn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTGpSb0RMWXMzZyt0QW80
            WnZzdXhqV01wdEhpekZVR1dnMU1UTDNuZTA4ClJJekdYYnovVld0ZDhkNUJXaEM5
            QnYzVjEzMmc0RHNEdWtwdWRGTHFlbWsKLS0tIHpPSnlSQnkyWUYrT0tpMFR4SVJM
            L3I0YVNIU2VEdjZkZ3lrYWRwSEtJTVEKIiZ+XeDkwk4CKcoSbSUra8ytEdtIIM9k
            FeDzckcE/AlHiRavs+GfRihTwgcOOgQKJ7HX0e7DhzfGxvNSAS2/Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T03:22:02Z"
    mac: ENC[AES256_GCM,data:vzZwEZrBqRf67p2+f/seAOCQ8q60t7ZKcHWTUWZiuBmDGxKhXM2PB08j8Pnk3Mktk5qYC3iaxj49IudaLDlVe8tPJJ1uCYX295ZmqdutczbmcMeHL7pvke3NoT3HUpSea/FKkxgwSuCJMDIAxVhQ8VJCN+lDSCdRiojrnba8/Kw=,iv:KBnymbVZBih+wu8blLSwvXA5OtWPHZAVDA3DEuTHCv8=,tag:95I5dUVh2a/ELy8tag++dQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.12.2
