keycloak_db_password: ENC[AES256_GCM,data:K0nw9N1Zs1epsjGJeB7rECHXJb1IeUOp,iv:UbIp5FYTh7s+JLlPiAM4dVoo5M2Bb4YOtaASaigoYt4=,tag:ImsU5c9xMV5yXBv++vs9UA==,type:str]
keycloak_redis_password: ENC[AES256_GCM,data:z/9tRSVr7dlGvqYJM71FNVNtP2KXaP/J,iv:l19nVlbIwQhg9Wf2S5xqOPm5bfkc1dYM0iJwQpMJ3Eg=,tag:T6PtMENvJPthR5tbV6GiyQ==,type:str]
keycloak_secret_key: ENC[AES256_GCM,data:vpXEf5DyMd6kZxNlx7pxEaoRSL8BceAw4cq/HjlWH04=,iv:vpiu8FnOjBPQ0s4KYcLDIZ9hEu5c43MoBTgoTZ7rsGo=,tag:BFCP6odvnGJdpc6uFaoTsg==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:yXzKALAwnAASSWH9vqiCYSyWPT17eVUn,iv:Dy73iRhVF4a9Nr1/pvObGZZxu0hn55/CQCZ/fUyqZ1w=,tag:lCfjl9XyLBoOan9zg2zciw==,type:str]
alert_smtp_user: ENC[AES256_GCM,data:U1LYddTeRA1l,iv:5vN/3gK+AE5VA/y/fMiwIwizlhTDL8tDwKlnZcvi7HA=,tag:XodCJAmt6dHeeGIkMNPEXA==,type:str]
alert_smtp_password: ENC[AES256_GCM,data:08Kf0B3oRu/W+3t5VrrQ6NcQf6/XfrCoa/cYh0nuZbWoKzEwRNZtsUE3BRA=,iv:f4sjoXXqTK8fgmRdrlvUW7V0flFUV+hXBw8WnDUwR00=,tag:c63YdLXlRPbmNsFFSeQwmQ==,type:str]
sops:
    age:
        - recipient: age10q0tj8gewf6rgx8plzz0lh9z8mamha6zw5qa7k2ea0d7q7kt8f5srrzmmn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTGpSb0RMWXMzZyt0QW80
            WnZzdXhqV01wdEhpekZVR1dnMU1UTDNuZTA4ClJJekdYYnovVld0ZDhkNUJXaEM5
            QnYzVjEzMmc0RHNEdWtwdWRGTHFlbWsKLS0tIHpPSnlSQnkyWUYrT0tpMFR4SVJM
            L3I0YVNIU2VEdjZkZ3lrYWRwSEtJTVEKIiZ+XeDkwk4CKcoSbSUra8ytEdtIIM9k
            FeDzckcE/AlHiRavs+GfRihTwgcOOgQKJ7HX0e7DhzfGxvNSAS2/Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T21:09:38Z"
    mac: ENC[AES256_GCM,data:jSyEuzZAYlIqc06T4Jh17RMPXRHDqqIrgTfdh282R6ACTynoi1zcsu8fMjWmYqad2vByXo8Y8Gv1qB5z3FEazbVSQBfB5QuawMSCxyidS/AcfALuP2do3Uja1YM6SJ5PfdgiVIb8L7eF1WlGMxjWbn3xoYIvYXoJCSHS8Qf3cI8=,iv:wU6hla963R7z+IG/evuhPCIivbXysWKe4k1AIZeMMJg=,tag:g+0K1idBMiSQbAOvBlLFCg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.12.2
