njalla_api_token: ENC[AES256_GCM,data:grPT8rAokB+Qyiia0cMi+1GyGKbvJwMx4rSpv1il9tA=,iv:nMbcBSAlBLT/aY56JwVKE9ki/2CuXjvKnlNm7NibUkk=,tag:m6tDNZEuWVvD+EnvRank4Q==,type:str]
keycloak_db_password: ENC[AES256_GCM,data:s9kfxU4fl/arbR1g08s=,iv:651tmJCJchUqKanvvv98ec2T7rQUIdxAcVNGUBTtnYA=,tag:fSrBgj/PXajgkImQCaZRVA==,type:str]
keycloak_redis_password: ENC[AES256_GCM,data:oJrJ2qMXj2YKmNsIyjhAhSo=,iv:iePK4CyHNxUpR65u1LnAYs36YZO4t4DvU88f/9SeOys=,tag:lEyHPaDxjON8M0xshnkGxQ==,type:str]
keycloak_secret_key: ENC[AES256_GCM,data:4pdxJ1ISCYy8k19P1ScHjJwe,iv:DyTMOuuUFE2rHBabJKnuEg+ezVg6/3bJo5fLVXpqzTc=,tag:9hW/UIflr6Etd+kKpiVXMA==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:g9+UNe1VsmveUG2oIYAMNjpCyNE=,iv:pTSkmFG+1UUGbUBi4GmJK/uv+GZ8RrPnirDbeKJVwtM=,tag:JlPyhVhnkIYzVYBhYKPInw==,type:str]
sops:
    age:
        - recipient: age10q0tj8gewf6rgx8plzz0lh9z8mamha6zw5qa7k2ea0d7q7kt8f5srrzmmn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTGpSb0RMWXMzZyt0QW80
            WnZzdXhqV01wdEhpekZVR1dnMU1UTDNuZTA4ClJJekdYYnovVld0ZDhkNUJXaEM5
            QnYzVjEzMmc0RHNEdWtwdWRGTHFlbWsKLS0tIHpPSnlSQnkyWUYrT0tpMFR4SVJM
            L3I0YVNIU2VEdjZkZ3lrYWRwSEtJTVEKIiZ+XeDkwk4CKcoSbSUra8ytEdtIIM9k
            FeDzckcE/AlHiRavs+GfRihTwgcOOgQKJ7HX0e7DhzfGxvNSAS2/Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:56:57Z"
    mac: ENC[AES256_GCM,data:U/PnWr3w4wyKbCyxS+NhoCfOfgpB3z2fiWx1RT9AfET4gCtGC2Hq9bzi3jNMbwg9EC2UkQbS3glJLQ+RwYOiitSML3WWo9P4zaO0sMirG/5ifN6m0jTGkdC6UBr7MZatEq25CwFGopRDq9bPyS7FHpPQiWT5/VQFXPQo26bNBBU=,iv:jqXJJYzHP2ak7/Vk34Najds0CnC62nTieP3dlxwmqlE=,tag:oIOousKU9fKa+CwlME6CTQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.12.2
