# NOTE: Existing DNS records should be imported rather than recreated to avoid downtime.
# Use the import_existing_records.sh script to generate import commands.

# -------------------------
# Proton Mail — MX
# -------------------------
resource "njalla_record_mx" "mx_primary" {
  domain   = "wilkesliberty.com"
  name     = "@"
  content  = "mail.protonmail.ch."
  priority = 10
  ttl      = 3600

  lifecycle {
    prevent_destroy = true
  }
}

resource "njalla_record_mx" "mx_secondary" {
  domain   = "wilkesliberty.com"
  name     = "@"
  content  = "mailsec.protonmail.ch."
  priority = 20
  ttl      = 3600

  lifecycle {
    prevent_destroy = true
  }
}

# -------------------------
# Proton Mail — Verification (TXT)
# Domain verification record required by Proton Mail
# -------------------------
resource "njalla_record_txt" "proton_verification" {
  domain  = "wilkesliberty.com"
  name    = "@"
  content = "protonmail-verification=${var.proton_verification_token}"
  ttl     = 10800 # 3h as shown in Njalla

  lifecycle {
    prevent_destroy = true
  }
}

# -------------------------
# Email SPF (TXT) — combined for Proton Mail (inbound) + Postmark (outbound transactional)
# Ensure only ONE SPF record at apex.
# -------------------------
resource "njalla_record_txt" "spf" {
  domain  = "wilkesliberty.com"
  name    = "@"
  content = "v=spf1 include:_spf.protonmail.ch include:spf.mtasv.net ~all"
  ttl     = 3600

  lifecycle {
    prevent_destroy = true
  }
}

# -------------------------
# Postmark — Return-Path / Custom Bounce Domain (CNAME)
# Improves DMARC alignment for outbound from Postmark.
# Postmark fixed CNAME target.
# -------------------------
resource "njalla_record_cname" "postmark_bounces" {
  domain  = "wilkesliberty.com"
  name    = "pm-bounces"
  content = "pm.mtasv.net."
  ttl     = 3600
}

# -------------------------
# Postmark — DKIM (TXT)
# Per-domain DKIM key generated by Postmark. After adding the domain in
# Postmark > Sender Signatures > Domains > wilkesliberty.com, paste the
# DKIM TXT value into terraform.tfvars as `postmark_dkim_value`.
#
# Selector is "<random>._domainkey" provided by Postmark; selector and value
# both come from their dashboard.
# -------------------------
resource "njalla_record_txt" "postmark_dkim" {
  count   = var.postmark_dkim_value != "" ? 1 : 0
  domain  = "wilkesliberty.com"
  name    = var.postmark_dkim_selector
  content = var.postmark_dkim_value
  ttl     = 3600
}

# -------------------------
# Proton Mail — DKIM (3 CNAMEs)
# Paste exact targets from Proton dashboard into terraform.tfvars
# -------------------------
resource "njalla_record_cname" "dkim1" {
  domain  = "wilkesliberty.com"
  name    = "protonmail._domainkey"
  content = var.proton_dkim1_target
  ttl     = 3600

  lifecycle {
    prevent_destroy = true
  }
}

resource "njalla_record_cname" "dkim2" {
  domain  = "wilkesliberty.com"
  name    = "protonmail2._domainkey"
  content = var.proton_dkim2_target
  ttl     = 3600

  lifecycle {
    prevent_destroy = true
  }
}

resource "njalla_record_cname" "dkim3" {
  domain  = "wilkesliberty.com"
  name    = "protonmail3._domainkey"
  content = var.proton_dkim3_target
  ttl     = 3600

  lifecycle {
    prevent_destroy = true
  }
}

# -------------------------
# Proton Mail — DMARC (TXT)
# Start with p=quarantine; use p=none to monitor first if you prefer.
# -------------------------
resource "njalla_record_txt" "dmarc" {
  domain  = "wilkesliberty.com"
  name    = "_dmarc"
  content = "v=DMARC1; p=quarantine; adkim=s; aspf=s; rua=mailto:dmarc-reports@wilkesliberty.com; ruf=mailto:dmarc-failures@wilkesliberty.com; fo=1; pct=100"
  ttl     = 3600

  lifecycle {
    prevent_destroy = true
  }
}
