blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/wilkesliberty/infra/discussions
    about: Ask questions, share ideas, and discuss infrastructure topics
  - name: 📧 Emergency Contact
    url: mailto:admin@wilkesliberty.com
    about: For critical infrastructure issues or security concerns
  - name: 📖 Documentation
    url: https://github.com/wilkesliberty/infra/blob/master/README.md
    about: Read the project documentation and setup guides